// DUT file list
// Add DUT RTL files here

/home/eda/prj/wujian100/soc/E902_20191018.v
/home/eda/prj/wujian100/soc/ahb_matrix_top.v
/home/eda/prj/wujian100/soc/aou_top.v
/home/eda/prj/wujian100/soc/apb0.v
/home/eda/prj/wujian100/soc/apb0_sub_top.v
/home/eda/prj/wujian100/soc/apb1.v
/home/eda/prj/wujian100/soc/apb1_sub_top.v
/home/eda/prj/wujian100/soc/clkgen.v
/home/eda/prj/wujian100/soc/common.v
/home/eda/prj/wujian100/soc/core_top.v
/home/eda/prj/wujian100/soc/dmac.v
/home/eda/prj/wujian100/soc/dummy.v
/home/eda/prj/wujian100/soc/gpio0.v
/home/eda/prj/wujian100/soc/ls_sub_top.v
/home/eda/prj/wujian100/soc/matrix.v
/home/eda/prj/wujian100/soc/pdu_top.v
/home/eda/prj/wujian100/soc/pwm.v
/home/eda/prj/wujian100/soc/retu_top.v
/home/eda/prj/wujian100/soc/rtc.v
/home/eda/prj/wujian100/soc/sim_lib/PAD_DIG_IO.v
/home/eda/prj/wujian100/soc/sim_lib/PAD_OSC_IO.v
/home/eda/prj/wujian100/soc/sim_lib/STD_CELL.v
/home/eda/prj/wujian100/soc/sim_lib/fpga_byte_spram.v
/home/eda/prj/wujian100/soc/sim_lib/fpga_spram.v
/home/eda/prj/wujian100/soc/sms.v
/home/eda/prj/wujian100/soc/smu_top.v
/home/eda/prj/wujian100/soc/tim.v
/home/eda/prj/wujian100/soc/tim1.v
/home/eda/prj/wujian100/soc/tim2.v
/home/eda/prj/wujian100/soc/tim3.v
/home/eda/prj/wujian100/soc/tim4.v
/home/eda/prj/wujian100/soc/tim5.v
/home/eda/prj/wujian100/soc/tim6.v
/home/eda/prj/wujian100/soc/tim7.v
/home/eda/prj/wujian100/soc/usi0.v
/home/eda/prj/wujian100/soc/usi1.v
/home/eda/prj/wujian100/soc/wdt.v
/home/eda/prj/wujian100/soc/wujian100_open_top.v
