# =============================================================================
# Waveform Dump TCL Script for Xcelium/Verisium Debug
# Generated by UVM Testbench Generator
# =============================================================================
# Usage:
#   make run TC=xxx              (wave dump only, default IDA format)
#   make run_pp TC=xxx           (post-processing debug, wave only)
#   make run_pp TC=xxx DEBUG_LEVEL=full  (post-processing debug, full)
#   make run WAVE_FORMAT=fsdb TC=xxx     (FSDB format for Verdi)
#   make run WAVE_FORMAT=shm TC=xxx      (SHM format for SimVision)
#   make run WAVE_FORMAT=vcd TC=xxx      (VCD format)
# =============================================================================
# Wave Formats:
#   - ida:  Verisium Debug format (default, recommended for Xcelium)
#   - fsdb: Synopsys Verdi format (requires VERDI_HOME and PLI linking)
#   - shm:  SimVision format (legacy)
#   - vcd:  VCD format (portable but large)
# =============================================================================

# Get test name from environment or use default
if {[info exists ::env(TEST_NAME)]} {
    set test_name $::env(TEST_NAME)
} else {
    set test_name "wujian100_open_top_test"
}

# Get wave format from environment (ida/shm/vcd/fsdb), default is ida
if {[info exists ::env(WAVE_FORMAT)]} {
    set wave_format $::env(WAVE_FORMAT)
} else {
    set wave_format "ida"
}

# Get IDA output directory from environment
if {[info exists ::env(IDA_DIR)]} {
    set ida_dir $::env(IDA_DIR)
} else {
    set ida_dir "."
}

# Get FSDB output directory from environment
if {[info exists ::env(FSDB_DIR)]} {
    set fsdb_dir $::env(FSDB_DIR)
} else {
    set fsdb_dir "."
}

# Get debug level: wave (default) or full
# wave: waveform only (smaller database)
# full: waveform + SV flow + log (larger database, more debug info)
if {[info exists ::env(DEBUG_LEVEL)]} {
    set debug_level $::env(DEBUG_LEVEL)
} else {
    set debug_level "wave"
}

# Create output directories if they don't exist
if {$wave_format eq "ida"} {
    file mkdir $ida_dir
}
if {$wave_format eq "fsdb"} {
    file mkdir $fsdb_dir
}

# Set database path based on format
if {$wave_format eq "ida"} {
    set db_path "${ida_dir}/${test_name}.ida"
} elseif {$wave_format eq "fsdb"} {
    set db_path "${fsdb_dir}/${test_name}.fsdb"
} else {
    set db_path "${test_name}"
}

puts "======================================================"
puts " Verisium Post-Processing Debug Configuration"
puts "======================================================"
puts " Test Name    : $test_name"
puts " Wave Format  : $wave_format"
puts " Debug Level  : $debug_level"
puts " Database     : $db_path"
puts "======================================================"

# Create database and setup probes based on format
if {$wave_format eq "ida"} {
    # -----------------------------------------------------
    # IDA format for Verisium Debug (recommended)
    # -----------------------------------------------------
    # Open IDA database with full path
    ida_database -open -name $db_path
    puts "INFO: Created IDA database: $db_path"
    
    if {$debug_level eq "full"} {
        # -----------------------------------------------------
        # Full Debug Mode: Wave + SV Flow + Log
        # Provides complete post-processing debug capability
        # -----------------------------------------------------
        puts "INFO: Full debug mode - recording wave + SV flow + log"
        
        # Record log messages (UVM_INFO, UVM_WARNING, UVM_ERROR, etc.)
        ida_probe -log
        puts "INFO: Log recording enabled"
        
        # Record SystemVerilog flow (code execution order)
        # -sv_flow records the order of SV code execution
        # Exclude UVM package to reduce database size
        ida_probe -sv_flow -ignore_sv_packages="uvm_pkg"
        puts "INFO: SV flow recording enabled (excluding uvm_pkg)"
        
        # Record waveforms with full hierarchy
        ida_probe -wave -wave_probe_args="tb_top -depth all -all -memories"
        puts "INFO: Waveform recording enabled for tb_top"
        
    } else {
        # -----------------------------------------------------
        # Wave Only Mode (default): Smaller database, faster
        # -----------------------------------------------------
        puts "INFO: Wave-only mode - recording waveforms"
        
        # Record waveforms only
        ida_probe -wave -wave_probe_args="tb_top -depth all -all -memories"
        puts "INFO: Waveform recording enabled for tb_top"
    }
    
} elseif {$wave_format eq "shm"} {
    # -----------------------------------------------------
    # SHM format (legacy SimVision format)
    # -----------------------------------------------------
    database -open $test_name -into ${test_name}.shm -default -shm
    puts "INFO: Created SHM database: ${test_name}.shm"
    
    # Use standard probe command for SHM
    probe -create tb_top -depth all -all -memories -shm
    puts "INFO: SHM probes created for tb_top"
    
} elseif {$wave_format eq "vcd"} {
    # -----------------------------------------------------
    # VCD format (standard, portable but large)
    # -----------------------------------------------------
    database -open $test_name -into ${test_name}.vcd -default -vcd
    probe -create tb_top -depth all -all -vcd
    puts "INFO: VCD probes created for tb_top"
    
} elseif {$wave_format eq "fsdb"} {
    # -----------------------------------------------------
    # FSDB format for Synopsys Verdi (requires Verdi PLI)
    # -----------------------------------------------------
    # Check if Verdi PLI is available
    if {[info exists ::env(VERDI_HOME)] || [info exists ::env(NOVAS_HOME)]} {
        set verdi_home [expr {[info exists ::env(VERDI_HOME)] ? $::env(VERDI_HOME) : $::env(NOVAS_HOME)}]
        puts "INFO: Verdi PLI detected at: $verdi_home"
    } else {
        puts "WARNING: VERDI_HOME or NOVAS_HOME not set. FSDB dump may not work."
        puts "WARNING: Please set VERDI_HOME or NOVAS_HOME environment variable."
        puts "WARNING: Also ensure Verdi PLI is linked during compilation with:"
        puts "WARNING:   -loadvpi \${VERDI_HOME}/share/PLI/Xcelium/XCELIUM_64/novas.so:FSDBDumpVcdTask"
    }
    
    # Create FSDB file using system tasks
    # Note: This requires Verdi PLI to be linked during compilation
    set fsdb_file $db_path
    puts "INFO: Creating FSDB file: $fsdb_file"
    
    # For Xcelium, use 'call' command to invoke SystemVerilog tasks
    # fsdbDumpfile creates the FSDB file
    # fsdbDumpvars dumps signals (depth, scope, options)
    # +all: dumps memories, MDA signals, structs, unions, power, packed structs, and SVAs
    if {[catch {
        call fsdbDumpfile "$fsdb_file"
        puts "INFO: FSDB file created: $fsdb_file"
        
        # Dump all signals from tb_top with full depth
        # Syntax: fsdbDumpvars [depth] [scope] [options]
        # depth 0 = all levels, +all = dump everything
        call fsdbDumpvars 0 "tb_top" "+all"
        puts "INFO: FSDB dumpvars configured for tb_top with +all options"
        
        # Also dump SVA (SystemVerilog Assertions) if available
        if {[catch {
            call fsdbDumpSVA 0 "tb_top"
            puts "INFO: FSDB SVA dump enabled"
        } err_sva]} {
            puts "INFO: FSDB SVA dump not available (this is optional)"
        }
        
    } err]} {
        # If call commands fail, provide instructions for SV-based dump
        puts "ERROR: Could not create FSDB dump via TCL commands"
        puts "ERROR: $err"
        puts ""
        puts "Please ensure:"
        puts "1. Verdi PLI is linked during compilation:"
        puts "   -loadvpi \${VERDI_HOME}/share/PLI/Xcelium/XCELIUM_64/novas.so:FSDBDumpVcdTask"
        puts ""
        puts "2. Or add to your testbench SystemVerilog code:"
        puts "   initial begin"
        puts "     \$fsdbDumpfile(\"$fsdb_file\");"
        puts "     \$fsdbDumpvars(0, tb_top, \"+all\");"
        puts "     \$fsdbDumpSVA(0, tb_top);"
        puts "   end"
    }
    
} else {
    puts "WARNING: Unknown wave format '$wave_format', using IDA"
    file mkdir $ida_dir
    set db_path "${ida_dir}/${test_name}.ida"
    ida_database -open -name $db_path
    ida_probe -wave -wave_probe_args="tb_top -depth all -all -memories"
}

# -----------------------------------------------------
# Optional: Probe only DUT signals (faster simulation)
# -----------------------------------------------------
# ida_probe -wave -wave_probe_args="tb_top.u_wujian100_open_top -depth all -all -memories"

puts "======================================================"
puts " Debug probes configured successfully"
puts " After simulation, use: make vsm TC=$test_name"
puts "======================================================"

# Start simulation
run